### ISSUE TITLE
No such property: COMPILE_ONLY_CONFIGURATION_NAME 

### ISSUE THREAD

**Issue by Cristianjss** [bertramdev/asset-pipeline#188] opened 2017-11-17 02:09 UTC
I´m getting the following error, adding the version 

classpath "com.bertramlabs.plugins:asset-pipeline-gradle:2.14.6"

Failed to apply plugin [id 'asset-pipeline']
   > No such property: COMPILE_ONLY_CONFIGURATION_NAME for class: org.gradle.api.plugins.JavaPlugin

**Comment by davydotcom** [comment] 2017-11-17 12:20
running and older gradle version?

**Comment by francoiskha** [comment] 2017-12-09 22:36
Hi,
I have the same issue creating a brand new grails 3.3.2 project.

# Step to reproduce
1. create a une app via the `grails create-app` command.
2. in `build.gradle` change `gradle.plugin.com.energizedwork.webdriver-binaries:webdriver-binaries-gradle-plugin` version from `1.1` to `1.2` due to [another problem](https://github.com/energizedwork/webdriver-binaries-gradle-plugin/issues/4)
3. run `./grailsw help`

# Actual behavior

Got error below instead of help

```
| Resolving Dependencies. Please wait...
Cannot resolve reloading agent JAR: Could not resolve all dependencies for configuration ':agent'.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/fran/Code/grails-example/build.gradle' line: 24

* What went wrong:
A problem occurred evaluating root project 'grails-example'.
> Failed to apply plugin [id 'asset-pipeline']
   > No such property: COMPILE_ONLY_CONFIGURATION_NAME for class: org.gradle.api.plugins.JavaPlugin

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.84 secs
| Error Error initializing classpath: No such property: COMPILE_ONLY_CONFIGURATION_NAME for class: org.gradle.api.plugins.JavaPlugin (Use --stacktrace to see the full trace)
```

I had the same message using the Intellij `create Domain Class` functionality.

# environment
- grailsVersion=3.3.2
- gormVersion=6.1.8.RELEASE
- gradleWrapperVersion=3.5
- Operating System: macOS 10.13.1
- JDK Version: 1.8.0_152 - OpenJDK 64-Bit Server VM (Zulu 8.25.0.1-macosx) (build 25.152-b16, mixed mode)

**Comment by Cristianjss** [comment] 2017-12-14 00:05
You have to update your Gradle version to the lastest one, that works for me.

**Comment by francoiskha** [comment] 2017-12-14 18:07
Well thank you, I tried but it dit no work for me. 
Here is what I did : 

* editing `gradle.properties` , setting `gradleWrapperVersion=4.4`
* running `./gradlew wrapper` to update
* running `./grailsw help`

I still have the same error, maybe I missed something ?

**Comment by davydotcom** [comment] 2017-12-14 18:11
Theres a bug around this with grails wrapper. It doesnt default to using the cradle wrapper annoyingly. It uses whatever sdkman is set at by default

**Comment by francoiskha** [comment] 2017-12-14 19:42
OK, disabling sdkman works for me. Annoying bug indeed. 

Thank you very much.

**Comment by davydotcom** [comment] 2017-12-14 20:45
going to close this since its a grails wrapper issue

**Closed by davydotcom** 2017-12-14 20:45 UTC
