### ISSUE TITLE
Asset Pipeline Gradle in plugin breaks consuming web

### ISSUE THREAD

**Issue by ctoestreich** [bertramdev/asset-pipeline#60] opened 2015-12-07 23:37 UTC
When a plugin defines the asset-pipeline-gradle build dep, plugin apply and an asset closure inside it's build config - a consuming web application breaks when trying to load local assets (less, css, js).  The tag renders with <script... application.js> but without the ?compile=false and asking for the resource directly produces a 404.

In the example below the foo.css asset from the plugin is rendered and the background is green, but the parents level assets of application.js and application.css are not processed.  I have tried including the excluding the asset-pipeline-gradle from the web project to no avail.  It isn't until the plugin project removes the asset-pipeline-gradle reference that everything works.  

Example of the issue using grails 3.0.9 and asset-pipeline 2.6.9.

https://github.com/Grails-Plugin-Consortium/asset-pipeline-bug

Cheers.

**Comment by davydotcom** [comment] 2015-12-07 23:40
A plugin should not use asset pipeline gradle as a build dependency as assets are not processed until app phase

**Comment by ctoestreich** [comment] 2015-12-07 23:45
I get that but we have a situation where we have plugins that we run as web apps, such as out pattern library, which need both standalone and plugin capabilities.  We could split them, but it works great in grails 2.x today.

**Comment by ctoestreich** [comment] 2015-12-07 23:48
We have several nested infrastructures such as:

domain -> pattern-libray -> web -> app

where domain, pattern library and web are all plugins and the app is the only actual app.  We work mainly in web due to it containing shared web functionality.  The app only has some small tweaks as there are 16 different app artifacts. 

Having web run stand alone is important, as is using local plugin references from all the layers (for example).  This allows us to change core stuff and see it quickly in the brands without having to solve version/snapshot hell.

**Comment by ctoestreich** [comment] 2015-12-08 14:30
@davydotcom Another question - Is there any reason that the configuration for the plugin is in the build.gradle and not the application.yaml file? 

The above situation where a plugin can not define the asset-pipeline-gradle can not set properties like es5->es6 level support, minify and compile options, etc.

**Comment by davydotcom** [comment] 2015-12-08 14:31
The reason is gradle cannot interpret application.yml. Thats grails runtime config where as assets{} is gradle build config

**Comment by davydotcom** [comment] 2015-12-08 14:33
The reason your app doesn't work when you use that plugin is you've loaded a `assets/manifest.properties` onto the class path of the project which makes your web app assume its packaged. You need to make sure when packaging a plugin for use by a webapp that assetCompile task is not used. If you want to make a jar for a plugin runtime you can adjust that task to use assetCompile

**Comment by kevana** [comment] 2015-12-14 18:55
If we can't use asset pipeline gradle in plugins, is there another way to specify extra build-time includes? We have a plugin that provides font files in `grails-app/assets/fonts` and it looks like that directory isn't being included in the plugin jar. The examples I've seen for adding extra directories have used `assets { includes = ["fonts/*"] }` in build.gradle.

Plugin structure:
```
app
- web
- - pattern-library (has grails-app/assets/fonts)
- - domain
```

We can get around this by moving fonts under one of the default folders (images, javascripts, stylesheets), but it's not ideal.

**Comment by davydotcom** [comment] 2015-12-14 18:57
this is actually a bug in the grails gradle plugin that has since been fixed are you on the latest grails3 build?

**Comment by kevana** [comment] 2015-12-14 19:05
The project is on `3.0.9`, was it fixed in .10 or do we need `3.1.0.M3`?

**Comment by davydotcom** [comment] 2015-12-14 19:24
I would try 10 for sure

**Comment by kevana** [comment] 2015-12-14 19:34
Still seeing this error with `3.0.10` as soon as we add `classpath "com.bertramlabs.plugins:asset-pipeline-gradle:2.6.9"` to the dependencies block.
```
Error:(26, 0) Cannot cast object 'org.jfrog.gradle.plugin.artifactory.dsl.ArtifactoryPluginConvention@3539c456' with class 'org.jfrog.gradle.plugin.artifactory.dsl.ArtifactoryPluginConvention' to class 'org.jfrog.gradle.plugin.artifactory.dsl.ArtifactoryPluginConvention'
```

**Comment by davydotcom** [comment] 2015-12-14 21:09
what gradle version?

**Comment by kevana** [comment] 2015-12-14 21:09
2.9

**Comment by davydotcom** [comment] 2015-12-14 21:10
sure this isn't an artifactory plugin issue? asset-pipeline-gradle does not even reference this plugin

**Comment by kevana** [comment] 2015-12-14 21:14
We're guessing the Bintray and Artifactory plugins aren't getting along but haven't tracked down the root cause yet. For now we moved our fonts under the stylesheets directory. Thanks for the help

**Comment by davydotcom** [comment] 2016-04-22 17:39
fixed plugin support , added asset-pipeline-gradle to your grails 3 plugin...

```
apply plugin: 'asset-pipeline'
assets {
  packagePlugin = true
}
```

**Closed by davydotcom** 2016-04-22 17:39 UTC
Labels: bug
