### ISSUE TITLE
Assets from other subprojects are also bundled in succeeding subproject builds in a multiproject Gradle build

### ISSUE THREAD

**Issue by glenndepaula** [bertramdev/asset-pipeline#81] opened 2016-03-18 02:32 UTC
Hi, not sure if this is a known issue here or in the grails-asset-pipeline project. I have a multiproject Gradle (2.10) build that has multiple Grails subprojects, app1 and app2. I added an app1-dummy-stylesheet.css in app1, and an app2-not-empty-stylesheet.css in app2.

When I build the whole project, app1 will be built first then app2. But when I look at the logged messages on the console, I see this:

`...`
`Compressing File 18 of 24 - jquery-2.1.3`
`Processing File 19 of 24 - app1-dummy-stylesheet.css`
`Minifying File 19 of 24 - app1-dummy-stylesheet`
`Compressing File 19 of 24 - app1-dummy-stylesheet`
`Processing File 20 of 24 - application.css`
`Minifying File 20 of 24 - application`
`Compressing File 20 of 24 - application`
`Processing File 21 of 24 - errors.css`
`Minifying File 21 of 24 - errors`
`Compressing File 21 of 24 - errors`
`Processing File 22 of 24 - main.css`
`Minifying File 22 of 24 - main`
`Compressing File 22 of 24 - main`
`Processing File 23 of 24 - mobile.css`
`Minifying File 23 of 24 - mobile`
`Compressing File 23 of 24 - mobile`
`Processing File 24 of 24 - app2-not-empty-stylesheet.css`
`Minifying File 24 of 24 - app2-not-empty-stylesheet`
`Compressing File 24 of 24 - app2-not-empty-stylesheet`
`Finished Precompiling Assets`
`:app2:buildProperties`
`...`

The stylesheet from app1 is added to app2. I checked the generated app2 war file, the app1 stylesheet is in there.

![image](https://cloud.githubusercontent.com/assets/3130865/13866777/d2289fb6-ecf3-11e5-8425-8f14284cfe2f.png)

If this is an expected behavior, is there a work around to keep other assets from being added to the succeeding subproject builds?

**Comment by davydotcom** [comment] 2016-04-22 17:41
this may be resolved in 2.8.0

**Closed** 2016-05-22 13:32 UTC

**Comment by gschueler** [comment] 2016-10-28 16:29
Can we reopen this issue?  @davydotcom 

I have this problem in 2.10.0, using either Gradle 2.12 or 3.1.  

In a basic multiple subproject build, running `assetCompile` on project "A" is including assets from project "B".

Test project:

~~~
├── build.gradle
├── projA
│   ├── build.gradle
│   └── src
│       └── assets
│           └── js
│               └── projectA.js
├── projB
│   ├── build.gradle
│   └── src
│       └── assets
│           └── js
│               └── projectB.js
└── settings.gradle
~~~

build.gradle is the same for each subproject:

~~~ {.groovy}
plugins {
    id 'com.bertramlabs.asset-pipeline' version '2.10.0'
}

assets {
    verbose = true
    minifyJs = true
    minifyCss = true
    enableSourceMaps = false
    enableGzip = false
    configOptions = [:]

    minifyOptions = [
            languageMode     : 'ES5',
            targetLanguage   : 'ES5', //Can go from ES6 to ES5 for those bleeding edgers
            optimizationLevel: 'SIMPLE',
            angularPass      : false // Can use @ngInject annotation for Angular Apps
    ]

    excludes = [ '**/*.less', '**/*.html']

    packagePlugin = false //set to true if this is a library

    developmentRuntime = true

    jarTaskName = null

    from "${project.projectDir}/src/assets"
    println "eval: ${project.projectDir}/src/assets"
    compileDir = "${project.buildDir}/assets/resources"
}

~~~

output of `gradle assetCompile` in the root dir:

~~~
eval: /Users/greg/devel/assetp-test/projA/src/assets
eval: /Users/greg/devel/assetp-test/projB/src/assets
:projA:assetCompile
Processing File 1 of 4 - projectA.js
- Minifying File
- Writing File
Processing File 2 of 4 - js/projectA.js
- Minifying File
- Writing File
Processing File 3 of 4 - projectB.js
- Minifying File
- Writing File
Processing File 4 of 4 - js/projectB.js
- Minifying File
- Writing File
Finished Precompiling Assets
:projB:assetCompile
Processing File 1 of 4 - projectA.js
- Minifying File
- Writing File
Processing File 2 of 4 - js/projectA.js
- Minifying File
- Writing File
Processing File 3 of 4 - projectB.js
- Minifying File
- Writing File
Processing File 4 of 4 - js/projectB.js
- Minifying File
- Writing File
Finished Precompiling Assets

BUILD SUCCESSFUL

Total time: 2.794 secs
~~~

Also notice that the dir structure under `src/assets` gets flattened, and then the files are added with the correct dir structure as well.

build contents for `projA`:

~~~
projA/build
└── assets
    └── resources
        ├── js
        │   ├── projectA-d512f3b09b6ad9ffaa0846a4204e0af9.js
        │   ├── projectA.js
        │   ├── projectB-d512f3b09b6ad9ffaa0846a4204e0af9.js
        │   └── projectB.js
        ├── manifest.properties
        ├── projectA-d512f3b09b6ad9ffaa0846a4204e0af9.js
        ├── projectA.js
        ├── projectB-d512f3b09b6ad9ffaa0846a4204e0af9.js
        └── projectB.js

3 directories, 9 files
~~~

There is other weird behavior.  The first time I ran that command, the output was different for `:projA:assetCompile`

Also, this is really weird.  The first time I put together this test project, and ran "gradle assetCompile"... And it proceeded to include assets from a completely different project (!) which is not part of the test multiproject build. That was using gradle 2.12, so i tried switching to 3.1 but see mostly the same erroneous behavior.  Maybe that is caused by the gradle daemon caching some data?

Ok, I retested using `gradle --no-daemon` each time.  The output from `assetCompile` is slightly different than if I don't specify `--no-daemon`, although it still includes projectA files in projectB resources directory.

I would really like to use AssetPipeline for my projects but this bug is preventing me from doing so :(

**Comment by gschueler** [comment] 2016-10-28 18:18
Looking at the code a little bit, i suspect it is because `AssetPipelineConfigHolder` statically holds some of the configuration and "resolvers" used to load assets.  In a multiproject build, the asset dirs from both projects are added to the list within the same JVM, so it is getting dirty with other project data.  Similarly for a gradle daemon build, it would retain resolver paths from other unrelated projects!!

I will see if I can refactor this 😨  easily.  I'd really like to use this plugin...!

**Comment by gschueler** [comment] 2016-10-28 21:00
I think I found a workaround:

~~~ {.groovy}
assetCompile.doFirst {
    asset.pipeline.AssetPipelineConfigHolder.resolvers = []
}
~~~

This resets the resolvers list before running the assetCompile task.  This would probably not work if you use multiple threads, but for a single-threaded build, it does the trick.

The real fix will require refactoring AssetPipelineConfigHolder to not be a singleton

**Comment by davydotcom** [comment] 2016-10-28 23:37
Ah good find, the static is useful in development runtimes so this may be tricky , although not too difficult

**Comment by davydotcom** [comment] 2016-10-28 23:56
2.11.6 should fix your problems there

**Comment by gschueler** [comment] 2016-10-28 23:58
@davydotcom thanks! i will try it

**Comment by gschueler** [comment] 2016-10-31 18:37
@davydotcom confirmed that 2.11.6 seems to work properly for multiproject builds, thanks!
